site_name: UML-MCP Documentation
nav:
  - Home: index.md
  - API:
      - Tools: api/tools.md
  - Diagrams:
      - UML: diagrams/uml.md
  - Integrations:
      - Claude Desktop: integrations/claude_desktop.md
      - Cursor: integrations/cursor.md
  - Configuration: configuration.md
  - Examples: examples.md
  - Installation: installation.md

markdown_extensions:
  - toc
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search