# UV package manager configuration
# Install uv: pip install uv
# Or on Windows: winget install --id=astral-sh.uv -e
# Or via curl: curl -LsSf https://astral.sh/uv/install.sh | sh

[project]
name = "uml-mcp"
version = "1.2.0"
description = "UML diagram generation server with MCP interface"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

dependencies = [
    # Core dependencies
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
    "typer>=0.9.0",
    "rich>=13.6.0",
    "httpx>=0.24.1",
    "pydantic>=2.4.2",
    "python-multipart>=0.0.9",
    "python-dotenv>=1.0.0",
    "starlette>=0.27.0",

    # Diagram libraries
    "plantUML>=0.3.0",
    "graphviz>=0.20.1",

    # Additional utilities
    "pillow>=10.1.0",
    "jinja2>=3.1.2",
    "aiofiles>=23.2.1",
    "pytest>=7.4.3",

    "mcp>=1.2.0",
    "requests>=2.28.0",
    "python-dateutil>=2.8.2",
    "fastmcp>=0.1.0",

    # Platform-specific: uvloop for Linux/Mac only
    "uvloop>=0.17.0; sys_platform != 'win32'",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.1.0",
    "pre-commit>=2.20.0",
    "black>=23.9.1",
    "isort>=5.12.0",
    "flake8>=6.1.0",
    "mypy>=1.5.1",
    "pytest-asyncio>=0.21.1",
]

[tool.uv]
# UV-specific settings
dev-dependencies = [
    "pytest>=7.0.0",
    "pytest-cov>=4.1.0",
    "pre-commit>=2.20.0",
    "sphinx>=5.0.0",
    "pytest-asyncio>=0.20.0",
]

[tool.black]
line-length = 88
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
